travis:
  secure:
    BINSTAR_TOKEN: blKIyhz+eVwsihe/URcz/WhIz/hZ9ggeWEz35J5WRdflSQ+K0yrxiYUF0NgsvftInAIC4bFaNTihMf2uqmIB506WtksdszCBRqqNY+JKJw1x1UsuLnhPTljej1Z1Mbqa43wWgs3OHuW66S61NvRi4PAw4HNetibWF+O0ckD/F9Pc8PyPT7A9gTehv5RWMlXuL2SjgRvwX33dv4hA5p1WwoAsZHY+pMTHTPolv/ltpaPEfFzsETD2LyxjnywWwdvlBYgUv2yeGaxiu+Uk11HLde9JHBRw3ebkRlAoF7p5CuT+1nN4fm10iyZTHtVkPk/18NRlO9xefSdlwGDqe4ILBi1YeWP9dlp1G/JNPK8Pvq+RaXDZmTTNDipKXGzPWKFStVEbJzN+d4TCfI5Ze+tJxSFMvjBNTZdY+3AXJQ5YxBbu8mlddR1EA3pHv0G8r86VrMy+nVfE9SHrZjLUNrzVJRp127YP92nconXQkm/YJkGbnzLJFnxpTsyjHw0JyaPMd8UsPg2YwKubBgUD9FixhXp/zGlgsPmVfnAq4DUu1WcLDYAKK7M29kxkTT0HhaXqn3h83P3VA7fTi0F/FZmeFXWde5/7tsGqqO9y29OcN0iasuOwaSxCqwluJaCi7UlDLv1L4Fwom9T6bilOyMOItU05ROPjvG48G+PSLio8+nk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
